# Generated by Django 4.2.2 on 2023-07-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
