# Generated by Django 4.2.1 on 2023-06-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceTracker', '0003_source_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Income'},
        ),
    ]
