# Generated by Django 4.2.1 on 2023-06-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank='True', null=True, upload_to='images/profile'),
        ),
    ]
